---
title: "References"
date: "Junho de 2020"
---

# Referências utilizadas para a elaboração e desenvolvimento deste trabalho

******************************************************

## Livros e artigos

- [**Regressões geograficamente ponderadas**](https://edisciplinas.usp.br/pluginfile.php/4302556/mod_resource/content/0/Aula%209.pdf) --André Luis Squarize Chagas
- [**Seleção Stepwise**](http://www.portalaction.com.br/analise-de-regressao/2723-selecao-stepwise) --Portal Action
- [**Tipos de visuais no Power BI**](https://docs.microsoft.com/pt-br/power-bi/consumer/end-user-visual-type) --Microsoft
- [**Autocorrelação espacial**](https://edisciplinas.usp.br/pluginfile.php/4129212/mod_resource/content/1/Depend%C3%AAncia%20espacial.pdf) --Owsvaldo Santos Baquero
- [**How to embed http websites in your R presentation?**](https://medium.com/@slowpenscience/how-to-embed-http-websites-in-your-r-presentation-f2b2bcb7a277) --Brice Beffara
- [**Indicadores de autocorrelação local (exemplo do município de São Paulo)**](http://www.dpi.inpe.br/cursos/ser301/trabalhos/fred_lisa.pdf) --DPI (Divisão de Processamento de Imagens do INPE)
- [**Markdown cheat sheet**](https://paperhive.org/help/markdown) --Paper Hive
- [**Power BI: O que é e para que serve**](https://www.voitto.com.br/blog/artigo/o-que-e-power-bi) --Maytê Pereira
- [**Análise Espacial de Dados Geográficos**](http://www.dpi.inpe.br/gilberto/livro/analise/cap5-areas.pdf) --Marília Sá Carvalho, Gilberto Câmara, Oswaldo Gonçalves Cruz, Virgínia Correa
- [**GeoDa Documentation**](https://geodacenter.github.io/documentation.html) --Luc Anselin

******************************************************

## Funções e bibliotecas da comunidade de R

Algumas referências deste trabalho são baseadas no excelente material produzido pela comunidade de R ao redor do mundo. Exemplos de implementações foram adaptadas para as necessidades deste trabalho.

- [**FGVR**](https://github.com/ldaniel/fgvr) --Leandro Daniel, Rodrigo Gonçalves e Daniel Campos
- [**Spatial-Statistics**](https://github.com/ldaniel/Spatial-Statistics) --Leandro Daniel, Rodrigo Gonçalves, Daniel Campos e Ygor Lima


## Fonte de Dados

Abaixo todas as fontes de dados utilizadas no desenvolvimento deste estudo.

- [**Levantamento de Preços e de Margens de Comercialização de Combustíveis**](http://www.anp.gov.br/precos-e-defesa-da-concorrencia/precos/levantamento-de-precos) --ANP (Agência Nacional de Petróleo)
- [**Zoneamento Nacional de Recursos de Óleo e Gás 2017-2019**](http://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/zoneamento-nacional-de-recursos-de-oleo-e-gas-2017-2019) --EPE (Empresa de Pesquisa Energética)
- [**Malha Territorial de 2018**](ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2015/Brasil/BR/) --IBGE (Instituto Brasileiro de Geografia e Estatística)
- [**Estimativa de População 2019**](ftp://ftp.ibge.gov.br/Estimativas_de_Populacao/Estimativas_2019/estimativa_TCU_2019_20200427.xls) --IBGE (Instituto Brasileiro de Geografia e Estatística)
- [**PIB dos Municípios de 2010 a 2017**](ftp://ftp.ibge.gov.br/Pib_Municipios/2017/base/) --IBGE (Instituto Brasileiro de Geografia e Estatística)